services:
  postgres-db:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.8.0-python3.11
    container_name: airflow_init_runner
    depends_on:
      - postgres-db
    env_file:
      - .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-db:5432/airflow
    command: bash -c "airflow db migrate"

  airflow-webserver:
    image: apache/airflow:2.8.0-python3.11
    container_name: airflow_webserver
    user: root  # Mantém como root
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-db:5432/airflow
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.0-python3.11
    container_name: airflow_scheduler
    user: root  # Mantém como root
    restart: always
    depends_on:
      - postgres-db
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-db:5432/airflow
    command: scheduler

volumes:
  airflow-db-data:
